# Generated by Django 5.1 on 2024-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='test@mail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cellphone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
